### ISSUE TITLE
Publish to PowerShell Gallery

### ISSUE THREAD

**Issue by Sam-Martin** [yubu/psbbix-zabbix-api#1]
Hi, 
Love the module! Would you be able to publish it to the PowerShell gallery please?
Also, I'd be interested in contributing to this if you're open to it. Let me know on samjackmartin@gmail.com if you're interested.

Many thanks,

Sam

**Comment by yubu** [comment]
Don't think  this module is good/pro enough to be published in Gallery.
Hm... I'll try to find time for this and also for including the contributions.

Thanks,
-y

**Comment by yubu** [comment]
Published in gallery.
