### ISSUE TITLE
Set-ZabbixHost Error (fix inside)

### ISSUE THREAD

**Issue by adminded** [yubu/psbbix-zabbix-api#11]
First: Great module collection!

Currently I am getting the following error if I try to edit a Zabbix Host with the CMDLet Set-ZabbixHost:

```
get-zabbixHost host.example.com | Set-ZabbixHost -status 0

  code message            data
  ---- -------            ----
-32500 Application error. Incorrect value "" for unsigned int field "proxy_hostid".
```

The error is located in the following line of **psbbix.psm1**:
```	Line 510: 		[Parameter(ValueFromPipelineByPropertyName=$true)][string]$ProxyHostID,```

## FIX
Setting the $ProxyHostID to 0 (like it is set in the New-ZabbixHost CMDlet):
```[Parameter(ValueFromPipelineByPropertyName=$true)][string]$ProxyHostID=0```

Sorry for setting up an issue, but I am currently out of time to submit a pull request. I just wanted to document this error.

Regards

**Comment by yubu** [comment]
Yes. It's already fixed. Will release another alpha in a week/two.
Thanks

**Comment by yubu** [comment]
Fixed.

**Comment by adminded** [comment]
Thanks! Great work !
