### ISSUE TITLE
Connect-Zabbix sometimes causes Invoke-WebRequest to https sites to fail

### ISSUE THREAD

**Issue by leightonium** [yubu/psbbix-zabbix-api#15]
https://github.com/yubu/psbbix-zabbix-api/blob/50e169bec1ca6557800b08be3854cc5698712f9c/psbbix.psm1#L187

Zabbix server is on https with a valid ssl cert for the domain name. Running the scripts on Windows Server 2016 powershell 5.1.

After running connect-zabbix server.name.com and inputting creds it connects to the zabbix server saying version 3.4.14.
But if you run any invoke-webrequest https://www.google.com it fails with the error 'Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a send.'

But by commenting out the above line it appears to fix this problem.

**Comment by yubu** [comment]
I will look on this later. I recommend to use certain powershell session for zabbix only, because of saved session parameters, which may interfere with other web/rest related stuff.

**Comment by yubu** [comment]
Try to copy all from Finally{} to catch{} and comment out entire finally{} and let me know. I cant check this right now. Thanks.

**Comment by leightonium** [comment]
Moving the items in Finally to Catch also appears to fix the issue.

**Comment by yubu** [comment]
Excellent, I'll push the change later as alpha.6 will also update the Powershell Gallery.
Thanks!
