### ISSUE TITLE
Problem with connection to zabbix server

### ISSUE THREAD

**Issue by Growlert** [yubu/psbbix-zabbix-api#16]
Hello!
I am using Zabbix Server version 4.0.2 in my organization. When I'm trying to connect to server with command 'Connect-Zabbix 'ip-address' -noSSL', powershell throw me the error:
```
ПРЕДУПРЕЖДЕНИЕ: You're going to connect via insecure HTTP protocol. Consider to use HTTPS.
Seems SSL certificate is self signed. Trying with no SSL validation...
Invoke-RestMethod : Удаленный сервер возвратил ошибку: (404) Не найден.
C:\Program Files\WindowsPowerShell\Modules\psbbix\0.1.8\psbbix.psm1:166 знак:28
+ ... :zabSession=Invoke-RestMethod ("$URL/api_jsonrpc.php") -ContentType " ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
 
ERROR: Not connected. Try again.
```
Is it because module doesnt support this version of zabbix or something else?

**Comment by Growlert** [comment]
OK. Seems I fixed it by myself. Just changed the string in **psbbix.psm1** module file
from '$URL = $Protocol+"://$IPAddress/zabbix"' to '$URL = $Protocol+"://$IPAddress/"'

But now I see another error after got connected:
```
code message         data                                                    
  ---- -------         ----                                                    
-32602 Invalid params. Cannot call method "apiinfo.version" without parameters.
```
Dont know is it normal or it will affect some commands to run.

**Comment by Growlert** [comment]
The last error i caught was related to last stable psbbix module (I thought I installed the last alpha..). So after isnstaling 0.2.0 the issue resolved. But I still had to fix psm1 from first post, and I determine it caused by alias parameter in zabbix web server config, so when I type http://zabbix_server_name I instantly redirected to zabbix default page (by default it set to  http://zabbix_server_name/zabbix, as pointed in module).

**Comment by yubu** [comment]
According Zabbix API docs: https://www.zabbix.com/documentation/4.0/manual/api
Once you've set up the frontend, you can use remote HTTP requests to call the API. To do that you need to send HTTP POST requests to the api_jsonrpc.php file located in the frontend directory. For example, if your Zabbix frontend is installed under http://company.com/zabbix, the HTTP request to call the apiinfo.version method may look like this:

POST http://company.com/zabbix/api_jsonrpc.php HTTP/1.1
Content-Type: application/json-rpc
 
All this is for default zabbix frontend install: http(s)://company.com/zabbix.

Unfortunately i don't have zabbix 4.0 to test this. I'll look on this later. 
Thanks.

**Comment by yubu** [comment]
I've tested on default zabbix 4.0.5 install. All works fine.
Seems you have some frontend customization, which causes the above problem. As you've already found the solution i'll put this issue on hold. And will possibly add the ability to change the default URL by custom one.

**Comment by yubu** [comment]
Can you, please, check latest alpha.7 in your environment (you can just replace connect-zabbix function):
connect-zabbix IP -noSSL -URLCustomPath ""
Thanks.

**Comment by Growlert** [comment]
Thanks for the support!
I've tested it. Now it works like a charm with this option!

In addition I would like to leave some suggestions for future releases:
- add ability to search hosts by the element name, element group name, may be I miss something and it's already icluded in current release, but I found only searching by trigger name/ name like
something like this: **get-zabbixhost | where {$_.element -like 'memory*'}**;
- removing templates from host with options -clear or leaving all objects it made
something like this: **set-zabbixhost 'host' -removingtemplates -TemplateID 'ID' -clear/notclear** 

Great job anyway! This module helped me to bulk adding hosts to some groups by trigger name and also clearing template from hosts which in zabbix web u have to do it manually (just realize if u have move than 100 hosts to monitor).

**Comment by yubu** [comment]
Great. Thanks for the feedback. I'll release this alpha to the Powershell Gallery also.
For the first case try to play with `get-zabbixItem`: 
`Get-ZabbixHost | ? name -match hostname | Get-ZabbixItem | ? name -match memory`
And try to play with help. It have tons of examples:
`gzh * -p "memory|ram"`  --> look for yellow highlights

I'll implement the second request in near future. 
Cheers

**Comment by yubu** [comment]
I've double checked regarding host templates; You have two options:

1.  Replace template by another one == replace template with no clear:
`set-zabbixhost host -templateid id`
2. Unlink and clear from the host == -removeTemplates

So actually you can -removeTemplates current templates and assign new ones after == clear
Just replace with no -removeTemplates == noclear
Its a bit confusing but will give you what you want.

**Comment by Growlert** [comment]
OK. Now I got it =)
I found another reference to zabbix url mismatch in command:
`Set-ZabbixTrigger -url "http://ip_address" -status 1`
So I must specify the url parameter here. Don't know this is by design or maybe you fixed it already.

**Comment by yubu** [comment]
No!
parameters: jsonrpc, session, id and URL are related to your current zabbix session. There are also others that comes over pipeline. ex: `Get-ZabbixHost | ? name -eq sourceHost | Copy-ZabbixHost -HostName NewHost -IP 10.20.10.10`

Before using some new function pull the help, you'll find a lot of example: `gzh trigger` 
For  `gzh trigger -pattern status` you'll get:

> PS C:\>Get-ZabbixHost -HostName HostName | Get-ZabbixTrigger -ea silent | ? status -match 0 | ? expression -match "V:,pfree" | Set-ZabbixTrigger -status 1 -Verbose
    Disable trigger
    -------------------------- EXAMPLE 2 --------------------------
    PS C:\>Get-ZabbixTrigger -TemplateID (Get-zabbixTemplate | ? name -match "Template Name").templateid | ? description -match "trigger description" |  Set-ZabbixTrigger -status 1
    Disable trigger
    -------------------------- EXAMPLE 3 --------------------------
    PS C:\>Get-ZabbixHost | ? name -match server0[1-5,7] | Get-ZabbixTrigger -ea silent | ? status -match 0 | ? expression -match "uptime" | select  triggerid,expression,status | Set-ZabbixTrigger -status 1
    Disable trigger on multiple hosts
    -------------------------- EXAMPLE 4 --------------------------
    PS C:\>Get-ZabbixTemplate | ? name -match "Template" | Get-ZabbixTrigger | ? description -match triggerDescription | Set-ZabbixTrigger -status 0
    Enable trigger
>
Hope this helps.
