### ISSUE TITLE
Set-ZabbixHostGroupRemoveHosts does not work (fix inside)

### ISSUE THREAD

**Issue by Cypherke** [yubu/psbbix-zabbix-api#17]
If you dont add templates it uses null in de payload:

>     "params":  {
>                   "hostids":  [
>                                   "10339"
>                               ],
>                   "templateids":  [
>                                       null
>                                   ],
>                   "groupids":  [
>                                    38
>                                ]
>               },

which results in an error 
Can you please add [line 1737](https://github.com/yubu/psbbix-zabbix-api/blob/master/psbbix.psm1#L1737) and [line 1738](https://github.com/yubu/psbbix-zabbix-api/blob/master/psbbix.psm1#L1738) to the function?

**Comment by yubu** [comment]
I'll look on this on weekend.

**Comment by yubu** [comment]
I can't reproduce the problem. Send, plz., exact command you're invoking.

This will work for you without fix (Zabbix version 3.4):
Remove:
Get-ZabbixHostGroup | ? name -eq hostGroup | select groupid -ExpandProperty hosts | ? host -match hostsToRemove | Set-ZabbixHostGroupRemoveHosts
Test:
Get-ZabbixHostGroup | ? name -eq hostGroup | select name -ExpandProperty hosts

**Comment by Cypherke** [comment]
I 'm working on zabbix version (4.2.2) and I use the following line in my script:

Set-ZabbixHostGroupRemoveHosts -GroupID _groupid_ -HostID _hostid_ -Confirm:$false

and i get this error:

```
code message            data
---- -------            ----
-32500 Application error. No permissions to referred object or it does not exist!
```
For the sake of argument i tried your code too and it gives me the same error.
I threw the verbose payload as mentioned in my first post in postman, and i got the same error. However, if i remove the "templateids": [ null ] part... in postman, it works.

**Comment by yubu** [comment]
Try this quick fix and let me know:
$Body = @{
			method = "hostgroup.massremove"
			params = @{
				groupids = @($GroupID)
				# hostids = @($HostID)
				# templateids = @($TemplateID)
			}
			
			jsonrpc = $jsonrpc
			id = $id
			auth = $session
		}

		# Possible fix
		if ($HostID) {$Body.params.hostids=@($HostID)}
		if ($TemplateID) {$Body.params.templateids=@($TemplateID)}
		# End possible fix

**Comment by Cypherke** [comment]
This works as it's the fix i mentioned in my first post. Also tested on my 4.2.2 release.

**Comment by yubu** [comment]
Ok. Thanks!
