### ISSUE TITLE
convertTo-epoch

### ISSUE THREAD

**Issue by JohPAM** [yubu/psbbix-zabbix-api#18]
I received an error when the function _convertTo-epoch_ was used. The error is: New-TimeSpan : Cannot bind parameter 'End'. Cannot convert value "10/24/2019 07:17:16" to type "System.DateTime". Error: "String was not recognized as a valid DateTime.".

I've solved this by dynamically retreiving the datetime format from the local computer. Source: [https://blogs.technet.microsoft.com/dsheehan/2017/09/24/powershell-datetime-throws-the-error-string-was-not-recognized-as-a-valid-datetime/](url)

`# Extract the default Date/Time formatting from the local computer's "Culture" settings, and then create the format to use when parsing the date/time information
$CultureDateTimeFormat = (Get-Culture).DateTimeFormat
$DateFormat = $CultureDateTimeFormat.ShortDatePattern
$TimeFormat = $CultureDateTimeFormat.LongTimePattern
$DateTimeFormat = "$DateFormat $TimeFormat"

$Date = Get-Date $Date -format $DateTimeFormat
(New-TimeSpan -Start (Get-Date -Date "01/01/1970") -End $date).TotalSeconds`

Regards JohPAM

**Comment by yubu** [comment]
Hi JohPAM,

My function will work if you'll provide the valid DateTime formatted string. You can provide any windows supported DateTime format as parameter the following way;
> convertTo-epoch (**get-date** -date "05/24/2015 17:05")
 date -f O | convertTo-epoch | convertFrom-epoch
 date -date  "24/May/2015 1:30pm" | convertTo-epoch | convertFrom-epoch

If format is not valid  (**get-date** -date "05/24/2015 17:05") will fail.
Sometimes it will also work if input String (without **get-date -date ""**) will be in valid DateTime format, like above "24/May/2015 1:30pm". This is just power of Powershell :). Look on function help it never suggests to use just String as input.
 
In your case your input was the string. And you have converted it to DateTime format within the function and not as parameter: 
> $Date = **Get-Date** $Date -format $DateTimeFormat

I'm not using any conversion in the code, just formatting the input as it already should be in DateTime format:
>$date=$date -f "mm/dd/yyyy hh:mm"

I'll add DateTime format validation to input string and catch the error with descriptive message.

Thanks for input!
Yubu

**Comment by yubu** [comment]
JohPam,

You can download and test the updated epoch-time-converter from my helpers project:
https://raw.githubusercontent.com/yubu/ps.helpers/master/Convert-EpochTime.ps1

Hope this will help,
Regards.
