### ISSUE TITLE
Time Zone API Maintance 

### ISSUE THREAD

**Issue by guilhermerezendemarques** [yubu/psbbix-zabbix-api#19]
How will I change the time zone for the New Zabbix Maintance function? In my case the script sets 3 hours below my local time. My time zone is Brasil / São Paulo / Brasilia. -3UTC

**Comment by guilhermerezendemarques** [comment]
I am creating the date through a variable in Powershell
Ex:  {New-ZabbixMaintenance -HostID (Get-ZabbixHost | ? name -match $hostname).hostid -MaintenanceName $maintance -MaintenanceDescription $maintance -ActiveSince $startdate -ActiveTill $enddate -TimeperiodStartDate $startdate }

**Comment by yubu** [comment]
Hey,
Sorry for delay.
Run: gzh maintenance
You'll see plenty of examples regarding time. StartDate = (get-date).addHours(3)
 All depends on your local PC/Laptop setting and Zabbix server settigs...

Hope it helps.
-y

**Comment by yubu** [comment]
Hope all is OK.
