### ISSUE TITLE
Connect-Zabbix -User Fails

### ISSUE THREAD

**Issue by bingo-the-pyro** [yubu/psbbix-zabbix-api#20]
Trying to use this method to connect to zabbix:
	.Example: Connect-Zabbix -User admin -Password zabbix -IPAddress zabbix.domain.net
But get error: New-ZabbixSession : A parameter cannot be found that matches parameter name 'User'.

Looking at the Function New-ZabbixSession there does not seem to be a parameter for user or password.

Am I missing something obvious?

**Comment by yubu** [comment]
Connect-Zabbix server/ip   will ask you for user/password in windows powershell and powershell core.
-user user -password password won't work.
Use the help to get examples: gzh session -p connect

**Comment by yubu** [comment]
Seems all is OK.

**Comment by bingo-the-pyro** [comment]
Sorry about the late reply - that example was from the help.
We are trying to internally automate an integration between two systems so a prompt for credentials stops that.
Would you be able to add in those parameters (especially since you've done such a great job of the rest!!)? 
Additionally it looks like there is a minor syntax error at line 4969 which could be invalidating the rest of the code.

**Comment by yubu** [comment]
Connect-Zabbix IPaddress -PScredential $someCreds will do what you want.

> 
 help -ex Get-Credential

 Example 7: Create a credential without prompting the user

    PS C:\>$User = "Domain01\User01"

    The second command uses the ConvertTo-SecureString cmdlet to create a secure string from a plain text password. The command uses the *AsPlainText* parameter to indicate that the string
    is plain text and the *Force* parameter to confirm that you understand the risks of using plain text.
    PS C:\>$PWord = ConvertTo-SecureString -String "P@sSwOrd" -AsPlainText -Force

    The third command uses the New-Object cmdlet to create a **PSCredential** object from the values in the $User and $PWord variables.
    PS C:\>$Credential = New-Object -TypeName "System.Management.Automation.PSCredential" -ArgumentList $User, $PWord

    This example shows how to create a PSCredential object that is identical to the object that Get-Credential returns without prompting the user. This method requires a plain text password,
    which might violate the security standards in some enterprises.

    The first command saves the user account name in the $User variable. The value must have the Domain\User or ComputerName\User format.

Regarding line 4969: It's just asks your permission to delete the Zabbix Application:

Get-ZabbixApplication | ? name -match "myRealyCuteApp" | Delete-ZabbixApplication
Confirm
Are you sure you want to perform this action?
Performing the operation "Delete" on target "myRealyCuteApp".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
applicationids
--------------
{3676}

Hope this helps,
-y
