### ISSUE TITLE
Why did you remove the URL parameter so it can't be used later on?

### ISSUE THREAD

**Issue by jonatastrife** [yubu/psbbix-zabbix-api#21]
https://github.com/yubu/psbbix-zabbix-api/blob/a6826eb74a889ca871e2ca9c2cbe4557b4c73e03/psbbix.psm1#L2409

**Comment by yubu** [comment]
Possibly because some kind of conflict with other functions. But from other hand it may be leftover from some test or just bug.
Reenable it and see what happens or just load older version.
-y

**Comment by yubu** [comment]
Closing. Seems all is ok.
