### ISSUE TITLE
Zabbix 4 New-ZabbixMaintenance

### ISSUE THREAD

**Issue by jmarsj** [yubu/psbbix-zabbix-api#22]
Hi yubu,

I have zabbix 4 server.
I am try your module but I get error when I want to create New-ZabbixMaintenance

New-ZabbixMaintenance -HostID $ComputerHostZabbix.hostid -GroupID $HostsGroups.groupid  -MaintenanceName "NewMaintenance" -ActiveSince (convertTo-epoch ((get-date).addhours(0)).ToUniversalTime()) -ActiveTill (convertTo-epoch ((get-date).addhours(+7)).ToUniversalTime()) -TimeperiodPeriod (4*3600)

I get the next error
-32602 Invalid params. Incorrect value "0" for unsigned int field "every".

I uset the vervose option I'm getting the netx:

"timeperiods":  [
                                       {
                                           "timeperiod_type":  0,
                                           "every":  0,
                                           "start_time":  0,
                                           "month":  0,
                                           "dayofweek":  0,
                                           "start_date":  null,
                                           "day":  0,
                                           "period":  14400
                                       }
                                   ],

Could you help me??

**Comment by yubu** [comment]
Hi,
Sorry for delay. 
Use only -HostId or only -GroupID as parameters. You don't need both. 
The logic is this: 

- If you have a group of hosts, and your host is within the group - you don't need to provide explicitly this single host.

- If you don't have a group or want maintenance for one/few hosts - you don't need to provide the group parameter.

Look at examples:
`get-help -ex New-ZabbixMaintenance`
`gzh maintenance`

-y

**Comment by yubu** [comment]
Seems all is ok.
