### ISSUE TITLE
Proxy Host ID not being passed to Set-ZabbixHost

### ISSUE THREAD

**Issue by m3t4Lm4n** [yubu/psbbix-zabbix-api#23]
If zabbix host is monitored via proxy after executing Set-ZabbixHost in pipeline, proxy_hostid is not being passed to -ProxyHostID instead proxy_hostid is set to 0.

```
Get-ZabbixHost name | Select name, proxy_hostid

name                              proxy_hostid
----                              ------------
name                              1234

Get-ZabbixHost name | Set-ZabbixHost -GroupID 1,2

hostids
-------
{10}

Get-ZabbixHost name | Select name, proxy_hostid

name                              proxy_hostid
----                              ------------
name                              0
```

**Comment by yubu** [comment]
You're right. This is not implemented. As a workaround, you can explicitly add -ProxyHostID as a parameter to Set-ZabbixHost.
-y

**Comment by m3t4Lm4n** [comment]
That's what I did but at first it broke monitoring on many production hosts as I was not expecting such behavior. Just wanted to point this out for others using this module. Are you planning to fixing this?

**Comment by yubu** [comment]
This is from beginning of Readme file:

 **Warning:**
**Be careful. Especially with the mass delete and the mass update.**
Bugs happen. Use on your own risk.

**Experimental:**
Get-ZabbixHostInventory 

And i would add this: This module is 6.5K lines of code given to you for free. If you would read the readme, look on the examples and test on few machines before running in production, so possibly it would not break your environment...
