### ISSUE TITLE
test-connection only uses ICMP pings, this fails when zabbix is behind a NLB 

### ISSUE THREAD

**Issue by leightonium** [yubu/psbbix-zabbix-api#25]
https://github.com/yubu/psbbix-zabbix-api/blob/0560c95dcf8903c4925988c7781fdc8c0589c12c/psbbix.psm1#L165

Our zabbix server is hosted behind an aws nlb which does not respond to pings. This causes this powershell module unable to connect "zabbix.domain.com is unavailable"

The test should be that a http/https connection is successful.

**Comment by yubu** [comment]
Zabbix server may run on any of ~64K ports, either http or https.
You can comment out this line as workaround.

Thanks for stopping by,
-y

**Comment by jmarsj** [comment]
Workarround
$ZabbixOnline = Test-NetConnection -ComputerName computername -Port 80
If ($ZabbixOnline.TcpTestSucceeded -like $true) {
blablabla
}else{
blablabla
}
