### ISSUE TITLE
Function Get-ZabbixHistory

### ISSUE THREAD

**Issue by dialod** [yubu/psbbix-zabbix-api#26]
Good afternoon ! Need your help. I'm using Zabbix version 4.4.5. The task was to obtain data from history from data elements for a certain period. Then this data will be processed in another program and reports will be built. For example: how many pages were printed on the printer per day, week, month. 
I tried to substitute my values ​​in the Get-ZabbixHistory -ItemID command (get-zabbixhost |? Name -match "server" | Get-ZabbixItem |? Name -match "system information").Itemid 
Where I specified the host name instead of "server", and " system information "replaced with a data item. 
It turned out Get-ZabbixHistory -ItemID (get-zabbixhost |? Name -match "dc1" | Get-ZabbixItem |? Name -match "CPU Load").Itemid No values ​​were received. 

Then I tried the command Get-ZabbixHistory -ItemID (get-zabbixhost -hostname "dc1" | Get-ZabbixItem -webitems -ItemKey "CPU Load" -ea silent) .itemid -TimeFrom (convertTo-epoch (get-date) .adddays (- 10)) | select itemid, @ {n = "clock (UTC-5)"; e = {(convertfrom-epoch $ _. clock) .addhours (-5)}},value 

The values ​​were received but not from the host "dc1" but with different hosts and their data elements. What am I doing wrong ? If it is possible in more detail how it is possible to realize my task.

**Comment by yubu** [comment]
Look. You just copy/pasting the values, but possibly you don't have the items you try to evaluate. 
First of all find out what items do you have in your Zabbix. Start to play with Get-ZabbixItem. 
Run `gzh item` to get examples how to use Get-Zabbix item.
Then do the same with Get-ZabbixHost `gzh host`.
Once you'll see how these commands are working, you can move to Get-ZabbixHistory. 

Split commands a do them one by one. 
Example:
`Get-ZabbixHistory -ItemID (get-zabbixhost | ? name -match "server" | Get-ZabbixItem | ? name -match "system information").itemid`

`Get-ZabbixHost | select name`
`get-zabbixhost | ? name -eq "<One of the names you got from Get-ZabbixHost>"`
`gzhst | ? name -eq "<One of the names you got from Get-ZabbixHost>" | Get-ZabbixItem`  --> you'll get all items for this specific host.
Then you can do `gzhst | ? name -eq "<One of the names you got from Get-ZabbixHost>" | Get-ZabbixItem | ? name -eq "<One of the items, you got from previous line.>"`

I hope, you got the idea.

-y

**Comment by dialod** [comment]
Thank you for responding to my message. You were right that the elements were not selected correctly. Reached the Get-ZabbixHistory command and received an error. 
Error example: New-TimeSpan: Cannot bind parameter 'End'. Cannot convert value "05/13/2020 05:40:16" to type "System.DateTime". Error: "String was not recognized as a valid DateTime.".
I tried the solution from the post "convertTo-epoch # 18" but it also did not help.

**Comment by yubu** [comment]
You need to use English US regional settings. If you're not, you need to provide your region correct format. Look region in Control Panel end/or run from powershell `(Get-Culture).DateTimeFormat`

And as i said in #18, try first just `get-date -date "05/24/2015 17:05"`. If this doesn't work. Find out correct format for your system region settings,

Look also here: https://blog.itpro.tv/get-date-powershell-cmdlet/

**Comment by dialod** [comment]
It seems to work out. There are no errors. But the output is strange data.
After entering the Get-ZabbixHistory -ItemID command (get-zabbixhost |? Name -match "dc1" | Get-ZabbixItem |? Name -match "CPU Load"). Itemid

The resulting values ​​are:
itemid clock value
------ ----- -----
143351 1589362631 vsrvmail1c01.office.int
143471 1589362631 vsrvproxy1.int
178151 1589362631 there
178211 1589362631 have
178210 1589362630 rsync: failed to connect to localhost (:: 1):
178930 1589362630 dc1-home.int
180432 1589362630 PASSED
180434 1589362630 WD-WX51D898623S
For some reason, Zabbix doesn’t give the story not on the Itemid of a particular host.
The problem is with "history"

**Comment by yubu** [comment]
Get-ZabbixHistory -ItemID **command** (get-zabbixhost |? Name -match "dc1" | Get-ZabbixItem |? Name -match "CPU Load"). Itemid

Why is **command** there?

> Get-ZabbixHistory -ItemID (receives parameter ItemID)
> ItemID=(get-zabbixhost | ? Name -match "dc1" | Get-ZabbixItem | ? Name -match "CPU Load"). Itemid
> If host dc1 has item "CPU Load" it should work, if not --> won't work.

**Comment by dialod** [comment]
Hello ! I will output the output of the commands in order.

1. get-zabbixhost | ? name -eq "dc1" | Get-ZabbixItem
All items are listed on the screen.

2. PS C:\Windows\system32> get-zabbixhost | ? name -eq "dc1" | Get-ZabbixItem | ? name -eq "Memory (free in %)"
We display information on the item "Memory (free in%)"

itemid                : 167315
type                  : 0
snmp_community        :
snmp_oid              :
hostid                : 11002
name                  : Memory (free in %)
key_                  : vm.memory.size[pavailable]
delay                 : 30s
history               : 30d
trends                : 180d
status                : 0
value_type            : 0
trapper_hosts         :
units                 : %
snmpv3_securityname   :
snmpv3_securitylevel  : 0
snmpv3_authpassphrase :
snmpv3_privpassphrase :

3. PS C:\Windows\system32> Get-ZabbixHistory -ItemID (get-zabbixhost | ? name -match "dc1" | Get-ZabbixItem | ? name -match "Memory (free in %)").itemid

And here they are incomprehensible data.

itemid clock      value
------ -----      -----
65884  1589399284 Microsoft Windows Server 2012 R2 Standard x64
143344 1589399284 srvbackup1.office
178204 1589399284 есть
179284 1589399284 david:x:1000:1000::/home/david:/bin/bash
143464 1589399284 vsrvbitrix2.int
165064 1589399284 nps1.int
178144 1589399284 есть
178143 1589399283 есть
161884 1589399283 active
161885 1589399283 raid1
162485 1589399283 Onln
162486 1589399283 WD
162489 1589399283 WDC
162491 1589399283 ATA
162492 1589399283 82
162493 1589399283 No
178203 1589399283 есть
179283 1589399283 evgeniy:x:1005:1005::/home/evgeniy:/bin/bash
169623 1589399283 rdhost2.int
143463 1589399283 vsrvbitrix3.office.int

What am I doing wrong ? Thank you in advance for your response.

**Comment by yubu** [comment]
Its powershell stuff -match vs -eq(ual). Go read about --> good to know. -match is evaluating a regex also.
`Get-ZabbixItem | ? name `**-eq**` "Memory (free in %)"`  **vs**
`Get-ZabbixItem | ? name `**-match**` "Memory (free in %)"`

Try `Get-ZabbixItem | ? name -match "Memory"`.
`Get-ZabbixItem | ? name -match 'Memory (free in %)'` (single quotes), and see how it goes. 

In any case i would avoid of using special characters in -match clause. If you really need this try to escape them with backtick **`**, but if you know exact string use -eq.

**Comment by dialod** [comment]
I completely forgot about it while I tried various combinations. Now everything worked out for me. Thanks for the help. Your advice helped a lot. I'm testing now.

**Comment by yubu** [comment]
Excellent! 
Be cautious with mass edit and mass delete, test first, Bugs happens.

**Comment by jame20** [comment]
Hi @yubu 

Firstly, I have to thank you for this awesome module.

I am also facing the date conversion error.

Input - Get-ZabbixAlert |  ? sendto -match Email | select alertid,subject

Error - Cannot bind parameter 'End'. Cannot convert value "04/24/2021 08:28:49" to type "System.DateTime".

I aslo tried 

get-date -date "05/24/2015 17:05" , but got error

But this format is working

get-date -date "24/05/2015 17:05"

How to alter Get-ZabbixAlert now?
