### ISSUE TITLE
Remove-ZabbixMaintenance -Confirm

### ISSUE THREAD

**Issue by jmarsj** [yubu/psbbix-zabbix-api#27]
Hi yubu,

I'm try Remove-ZabbixMaintenance -Confirm
Remove-ZabbixMaintenance -Name MaintenaceName -Confirm $true
Remove-ZabbixMaintenance -Name MaintenaceName -Confirm $false

I always get msgbox confirm popup. Is possible remove msgbox confirm popup?
![image](https://user-images.githubusercontent.com/45194130/84758945-60c30380-afc6-11ea-8c8b-4078fea1b560.png)

**Comment by yubu** [comment]
Try
Remove-ZabbixMaintenance -Name MaintenaceName -Confirm:$false

**Comment by yubu** [comment]
Seems all is ok.
