### ISSUE TITLE
'New-ZabbixTrigger' function not working

### ISSUE THREAD

**Issue by msarahr** [yubu/psbbix-zabbix-api#28]
There is a 'New-ZabbixTrigger' function, but the examples shown only for disabling and enabling triggers using 'Set-ZabbixTrigger'.
Can the 'New-ZabbixTrigger; be used to create new trigger with new description, expression, and severity?

**Comment by yubu** [comment]
Lol. This is a bug. The help was copied from Set-ZabbixTrigger and not changed. I'm not sure that this function was tested as needed, so be careful. The below should work, but you should check first:
`New-ZabbixTrigger -TriggerDescription 'Service status' -TriggerExpression '{Linux server:log[/var/log/system,Service .* has stopped].strlen()}<>0' -Status 0`

**Comment by yubu** [comment]
seems all is OK.
