### ISSUE TITLE
Please, add UTF-8 support

### ISSUE THREAD

**Issue by pashalvov** [yubu/psbbix-zabbix-api#29]
Hi, sorry for my English )
Then i make some request with Russian symbols i get no result, but if i make request by id i will get result.
If i add this strings in module right after `$BodyJSON = ConvertTo-Json $Body` problem is solved:
`$BodyJSON = [System.Text.Encoding]::UTF8.GetBytes($BodyJSON)`
`Write-Verbose "Convert BodyJSON to UTF-8"`
![image](https://user-images.githubusercontent.com/40241531/95675636-6e2d7a80-0bc1-11eb-9513-98aa677baea5.png)

Can you, please, add this in all module?

**Comment by yubu** [comment]
Hi Pasha,

I would parameterize this in some way to avoid the other problems with the text encoding. I'll look on this later.  The Holiday season is approaching, bringing a lot of work.

May be it's time to refactor entire module, but you know... 
Thanks

**Comment by pashalvov** [comment]
I'm not in a hurry, happy holidays. So far I've made edits to myself in psm1 and I'm in no hurry)))) Thank you.

**Comment by yubu** [comment]
Great to hear this. Hope all the rest is working ok for you.
Thanks.
