### ISSUE TITLE
Date Conversion Error in get-zabbixalert

### ISSUE THREAD

**Issue by jame20** [yubu/psbbix-zabbix-api#32]
Hi @yubu 

Firstly, I have to thank you for this awesome module.

I am also facing the date conversion error.

Input - Get-ZabbixAlert | ? sendto -match Email | select alertid,subject

Error - Cannot bind parameter 'End'. Cannot convert value "04/24/2021 08:28:49" to type "System.DateTime".

I aslo tried

get-date -date "05/24/2015 17:05" , but got error

But this format is working

get-date -date "24/05/2015 17:05"

How to alter Get-ZabbixAlert now?

**Comment by yubu** [comment]
Sorry for delay.
You need to use valid Windows date format.
Look here: https://github.com/yubu/psbbix-zabbix-api/issues/18
It may help.

**Comment by jame20** [comment]
Yes yubu...I referred both #18 and #26...But still am not able to clear it....My windows server supports this format "dd-MM-yyyy HH:mm".

Now my doubt is how and where do I change the date format?

**Comment by yubu** [comment]
All time formatting is happening on machine, the module is installed on. 
I will suggest the workaround for you:
End == get-date (default), and this is not working for you for some reason.
Use the parameter: `-TimeTill`
Look on examples: `gzh alert`. Examples 5,6 and 10. 
 
If your Zabbix server does not reside in the same TZ as you, you'll need to play with `.addhours`  to adjust the time difference, between you and Zabbix server.
Powershell always presents the time  in your local (client side) Time Zone, So if, let say your Zabbix Server in Singapore and you want to see Alert's real (Singapore) time, you'll need to add or remove the TZ difference .

Or you can try to implement the solution, suggested by  JohPAM, from https://github.com/yubu/psbbix-zabbix-api/issues/18
as alternative

**Comment by jame20** [comment]
Hi Yubu,

I tried the example 5 and got the below error

Get-ZabbixAlert -TimeFrom (convertTo-epoch (((get-date).ToUniversalTime()).addhours(-10))) -TimeTill (convertTo-epoch(((get-date).ToUniversalTime()).addhours(-2))) | ? sendto -match mail | ? subject -match "" | select @{n="Time(UTC)";e={convertfrom-epoch $_.clock}},alertid,sendto,subject
New-TimeSpan : Cannot bind parameter 'End'. Cannot convert value "05/18/2021 02:01:51" to type "System.DateTime". Error: "String was 
not recognized as a valid DateTime."
At C:\Program Files\WindowsPowerShell\Modules\psbbix\0.2.1\epoch-time-convert.ps1:61 char:58
+ ... (New-TimeSpan -Start (Get-Date -Date "01/01/1970") -End $date).TotalS ...
+                                                             ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-TimeSpan], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.NewTimeSpanCommand


And my zabbix server and windows server are in same time zone.

**Comment by yubu** [comment]
- You can use the dynamic Locale/Region configuration as pointed by JohPAM, in https://github.com/yubu/psbbix-zabbix-api/issues/18: 

Change these lines in ConvertTo-Epoch function in file epoch-time-convert.ps1

[Parameter(ValueFromPipeline=$true)]`[datetime]`$date

`$date=$date -f $((get-culture).DateTimeFormat.ShortDatePattern)`
(New-TimeSpan -Start (Get-Date -Date "01/01/1970") -End $date).TotalSeconds`

**Comment by jame20** [comment]
Hi Yubu,

Still am getting the same error.

Function convertTo-epoch {
[CmdletBinding()]
	[Parameter(ValueFromPipeline=$true)][datetime]$date
	
	if (!$psboundparameters.count) {help -ex convertTo-epoch  | Out-String | Remove-EmptyLines; return}
	
$date=$date -f $((get-culture).DateTimeFormat.ShortDatePattern)
(New-TimeSpan -Start (Get-Date -Date "01/01/1970") -End $date).TotalSeconds
}

**Comment by yubu** [comment]
So. Go control panel, region  and set English (United states). Start powershell. Check with Get-Culture. that you have 
```
CID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States)

```
Try if following command works: `convertTo-epoch (get-date) | convertFrom-epoch`
If yes, revert the region settings. In your current session will remian en-US, and in all rest will be yours default.

**Comment by yubu** [comment]
This may work:
```
$LocalCulture = Get-Culture
$date=$date -f $($LocalCulture.DateTimeFormat.ShortDatePattern + " " + $LocalCulture.DateTimeFormat.LongTimePattern)
```
