### ISSUE TITLE
Wrong check if parameter is present

### ISSUE THREAD

**Issue by sergey-mz** [yubu/psbbix-zabbix-api#34]
https://github.com/yubu/psbbix-zabbix-api/blob/0560c95dcf8903c4925988c7781fdc8c0589c12c/psbbix.psm1#L6391

`if ($OSName) `will return false if `$OSName=''`.
This makes it impossible to clear a field using this function.
Proper check should be `$MyInvocation.BoundParameters.Keys.Contains('OSName')`.
This will handle empty parameter values properly and clear them in Zabbix.
This applies to all lines 6391-6460

**Comment by yubu** [comment]
Noted. Thanks for fix. 
As i currently don't have Zabbix server to test the change, you have the fix and workaround would be  just insert the space (`$OSName=" "`). closing the issue.
