### ISSUE TITLE
Zabbix 5.x Support - Host Interface SNMP

### ISSUE THREAD

**Issue by bingo-the-pyro** [yubu/psbbix-zabbix-api#35]
Hi, any chance of updating for the newer version?

On 5.4 I have found adding a new host interface of SNMP fails with '-32602 Invalid params. Incorrect arguments passed to function.'

After researching there is now a whole details section for snmp https://www.zabbix.com/documentation/current/manual/api/reference/hostinterface/object#host_interface that was not there in 4.x - perhaps you could just adjust the hostinterface functions for this?
Thanks!

**Comment by bingo-the-pyro** [comment]
For anyone else looking, you can make this partially functional:
Edit psbbix.psm1
Find Function New-ZabbixHostInterface section
Scroll to $Body section and paste this under type = type
details = @{version=2; bulk=1; community={$SNMP_COMMUNITY}}

Obviously this hard codes those snmp settings, so someone more knowledgeable than I could make this work nicer.

**Comment by yubu** [comment]
:) I'll try if will find some free time.
