### ISSUE TITLE
 psbbix can`t find module "Find-String"

### ISSUE THREAD

**Issue by Mitruk5** [yubu/psbbix-zabbix-api#37]
Hello!
I`m tried to use gzh -list but every time i see:
                                                                                      
Install module Find-String from Powershell Gallery: install-module find-string -force. Unless this function won't work properly.

this module installed:

PS C:\WINDOWS\system32> Get-InstalledModule
Version    Name                                Repository           Description
-------    ----                                ----------           -----------
1.7.2      Find-String                         PSGallery            Find-String is a PowerShell script whose purpose...
0.2.1      psbbix                              PSGallery            Powershell Zabbix API

I tried to run the installation in debug mode, but did not see any errors in loading this module.
What im doing wrong?

PS version
Name             : ConsoleHost
Version          : 5.1.19041.1237

**Comment by Mitruk5** [comment]
I found a likely problem. I needed a module version 1.7.0

**Comment by yubu** [comment]
Hi, it should work with newer find-string 1.7.2 also.  But the only diff between 1.7.0 and 1.7.2 is that 1.7.2 is in Powershell Gallery. You can upgrade it after psbbix installation. Or comment out the line #95. I'm using find-string to color select-string's pattern for convenience.

**Comment by yubu** [comment]
Be careful, this module not tested with newer Zabbix versions.

**Comment by Mitruk5** [comment]
Thank you
