### ISSUE TITLE
New-ZabbixHost parameter for specifying a value for "Monitored by proxy" on host import.

### ISSUE THREAD

**Issue by thestraycat** [yubu/psbbix-zabbix-api#4]
Apologies if this is already doable but i couldn't find any info regarding specifying zabbix proxies during a host import....

**Comment by thestraycat** [comment]
Maybe just the option to specify proxy via:  -proxyid ?

**Comment by yubu** [comment]
Should work. Cant test however --> don't have proxies in my setup :(.
