### ISSUE TITLE
is there an ability to set the macro fields for a host?

### ISSUE THREAD

**Issue by gurban2013** [yubu/psbbix-zabbix-api#40]
trying to set host "hostname123" macro field "macroname" to value "AB123DC345"
dont see a way to do that in the read me.

**Comment by yubu** [comment]
You can't, sorry. This is very old module... not supported for a long time. You can look in psbbix.psm1 for function New-ZabbixTemplate, there is a commented-out parameter line with 'macro'. It may possibly help you.
