### ISSUE TITLE
Get Errot creating host

### ISSUE THREAD

**Issue by miquelangeld** [yubu/psbbix-zabbix-api#5]
Hi, I'm getting this error:
code    : -32500
message : Application error.
data    : No permissions to referred object or it does not exist!

when I try to create a host. My params look like this, when I try to create a host:

{
    "method":  "host.create",
    "params":  {
                   "host":  "FP221C3X",
                   "groups":  {
                                  "groupid":  "18"
                              },
                   "templates":  [
                                     {
                                         "templateid":  10186
                                     },
                                     {
                                         "templateid":  null
                                     },
                                     {
                                         "templateid":  null
                                     },
                                     {
                                         "templateid":  null
                                     },
                                     {
                                         "templateid":  null
                                     }
                                 ],
                   "status":  "0",
                   "interfaces":  {
                                      "port":  "10050",
                                      "dns":  "",
                                      "ip":  "192.168.0.50",
                                      "useip":  1,
                                      "type":  1,
                                      "main":  1
                                  }
               },
    "id":  "1",
    "jsonrpc":  "2.0",
    "auth":  "b495c7b6635873af9d78d1696114379c"
}

Maybe the problem is that the groups should be an array?

**Comment by yubu** [comment]
Create host within single group. Multiple groups is not supported.
I've added  Set-ZabbixHostGroup to manipulate groups in future release.

**Comment by elrj** [comment]
I get the same error if I use a GroupID with double digits. GroupIDs 1-9 work without issues. When I try to use a GroupID 10 or greater I get the 32500 error. Thank you

**Comment by mhoria** [comment]
Hello,
I have the same issue when trying to add a new host where the GroupID > 10. 
Any idea?
Thanks

**Comment by sleptsovsn** [comment]
I got the same error when using New-ZabbixHost:
-32500 Application error. No permissions to referred object or it does not exist

Did anyone figure out?

**Comment by yubu** [comment]
Should work with 9+ GroupID and TemplateID
